### ISSUE TITLE
Esclarecimento no texto

### ISSUE THREAD

**Issue by marado** [marado/mp#13]
O texto:

```Consagrar uma excepção para "utilização não comercial" não é suficiente, e é de difícil execução, porque a maior parte dos links são partilhados sem fins lucrativos, mas em plataformas que têm em si fins lucrativos.```

Tinha o seguinte comentário (que apaguei): `Não percebo esta. Paula?`

Fica aqui a nota de que é possível que ele precise de ser revisto. 

/cc @paulasimoes

**Comment by paulasimoes** [comment]
Não me lembro de ter escrito isso, deve estar no log. De qualquer forma percebo: a expressão "não comercial" dá sempre problemas porque ninguém sabe exactamente o que significa: eu posso estar a partilhar links sem fins comerciais, mas se o estiver a fazer no Twitter ou no Facebook, ambas as plataformas estão a fazer dinheiro com os conteúdos que lá estou a colocar.

**Comment by marado** [comment]
@EdSantos754 @paulasimoes vale a pena rever o texto para o tornar mais explícito, ou fica assim?

**Comment by EdSantos754** [comment]
Essa nota era em relação ao parágrafo que se seguia (e não em relação ao anterior).

> Não há necessidade de criar este direito conexo ao direito de autor, uma vez que os editores de imprensa podem usar a “presumption rule”, ou seja, os editores podem processar as plataformas em nome dos jornalistas, uma vez que a lei presume que aqueles agem no interesse dos jornalistas.

Já li um pouco e *acho* que percebi. Sugiro:
> Não há necessidade de criar este direito conexo ao direito de autor. Os editores de imprensa alegam que o objectivo desta medida é fazer cumprir, na prática, o direito de autor. Para tal seria suficiente a consagração de uma presunção legal que permita aos editores de imprensa agir judicialmente, em nome dos seus jornalistas, contra eventuais infracções.

**Comment by paulasimoes** [comment]
concordo com a sugestão do @EdSantos754
