### ISSUE TITLE
Sugestão para o texto a roxo

### ISSUE THREAD

**Issue by paulasimoes** [marado/mp#17]
"Infelizmente, este não é o único problema desta proposta. As discussões e votações nas várias comissões do Parlamento Europeu continuam a manter em cima da mesa os mesmos problemas. A votação na Comissão dos Assuntos Jurídicos, que é também a votação mais importante está marcada para finais de Abril. 
Precisamos de nos fazer ouvir pelos Eurodeputados!"

**Comment by paulasimoes** [comment]
O priberam não reconhece a palavra "practibilidade".
Texto: "Recordamos, que por motivos óbvios de interesse público e practibilidade, um comum título de notícia não é, por norma, objecto de direito de autor. Mas seria sujeito a este direito conexo."

Sugestão: Recordamos, que por motivos óbvios de interesse público e pelo facto de não ser original, um comum título de notícia não é, por norma, objecto de direito de autor. Mas seria sujeito a este direito conexo.

**Comment by EdSantos754** [comment]
Praticabilidade. Sorry, estava disléxico :P 

> "Recordamos que, dada a ausência de criatividade de um título de notícia - geralmente uma descrição factual - e também por motivos óbvios de interesse público e praticabilidade, um comum título de notícia não é, por norma, objecto de direito de autor. Mas seria sujeito a este direito conexo."

**Comment by EdSantos754** [comment]
> dada a ausência de criatividade de um título de notícia

A Paula diz que é ausência de originalidade. Eu acho que é de criatividade. Desempatas? :P

**Comment by EdSantos754** [comment]
> Infelizmente, este não é o único problema desta proposta. As discussões e votações nas várias comissões do Parlamento Europeu continuam a manter em cima da mesa os mesmos problemas. A votação na Comissão dos Assuntos Jurídicos, que é também a votação mais importante está marcada para finais de Abril. Precisamos de nos fazer ouvir pelos Eurodeputados!

Este texto (principalmente a última frase) não se enquadra numa carta dirigida ao MeP, mas numa carta dirigida ao público. Parece uma espécie de call to action, fora de contexto. Comecei a escrever qq coisa mas também não gostei.

Proponho que tentemos chegar a um texto comum aqui: https://etherpad.net/p/jk%C3%A7dokdsa09423
E continuemos a usar este tópico para comentar.

**Comment by marado** [comment]
> A Paula diz que é ausência de originalidade. Eu acho que é de criatividade. Desempatas? :P

Meti criatividade, e desempato para criatividade. Se quiserem alterar, abram um novo issue sff..

> Este texto (principalmente a última frase) não se enquadra numa carta dirigida ao MeP

Como já lá está, fica até chegarmos a um novo texto. Como este issue já está fechado (e não era sobre o tema) abri outro específico sobre isto: https://github.com/marado/mp/issues/19

**Comment by marado** [comment]
Texto final:

**Infelizmente, os filtros de upload não são o único problema desta proposta.** As discussões e votações nas várias comissões do Parlamento Europeu continuam a manter em cima da mesa diversas medidas que consideramos problemáticas. A votação na Comissão JURI é a **última oportunidade** que temos para dar algum **equilíbrio** ao direito de autor, **fazendo respeitar os direitos fundamentais dos cidadãos.**
