### ISSUE TITLE
remover "setas" entre secções

### ISSUE THREAD

**Issue by marado** [marado/mp#20]
Para termos um comportamento igual em firefox e chrome, vamos remover as "setas" entre as divisões (vistas apenas em chrome). Esta remoção tem a vantagem de resolver um problema em mobile (ou qualquer forma de visualizaão do site com uma largura pequena.

**Comment by paulasimoes** [comment]
@marado eu também vejo as setas no meu Firefox :-P Screenshot de como vejo em Firefox em anexo
![screenshot-2018-3-14 carta aberta ao eurodeputado antonio marinho e pinto](https://user-images.githubusercontent.com/12296/37414850-ff02175c-27a1-11e8-900c-a2e8c8cf1b81.jpg)

**Comment by EdSantos754** [comment]
Sempre vi as setas... e gosto delas :D

**Comment by marado** [comment]
Vou manter as setas e resolver só o problema que se vê em mobile, então.
