### ISSUE TITLE
mudar o background da primeira secção

### ISSUE THREAD

**Issue by marado** [marado/mp#21]
em chrome e firefox temos comportamentos e backgrounds diferentes, há que homogeneizar.

**Comment by paulasimoes** [comment]
@marado No site que o Eduardo enviou por email, e *no firefox* vejo a imagem por trás da foto do Marinho. talvez ele tenha usado código antigo?
Por outro lado, o site no meu firefox (chrome é igual) aparece o triangulo a branco e a seta. Logo **aquilo que vês no teu firefox não é o mesmo que eu vejo no meu firefox**

**Comment by EdSantos754** [comment]
Site actualizado. Não sei se ajuda...
