### ISSUE TITLE
Formatar melhor o texto dos detalhes do artigo 13º 

### ISSUE THREAD

**Issue by nmota** [marado/mp#22]
Considerando a dimensão do texto e algumas particularidades como a enumeração na "as plataformas não são juízes de direitos" o alinhamento ao centro não parece o mais indicado.
Também acho que se pode reorganizar o texto para aumentar a legibilidade.

**Comment by marado** [comment]
A reorganização de texto, se for para avançar, por favor apresentem uma proposta de alteração, num novo issue.

**Comment by nmota** [comment]
Quando referi reorganização no fundo queria dizer mais parágrafos. É mesmo preciso um novo issue? Já estou a preparar um pull request com tudo....

**Comment by marado** [comment]
O pull request serve :-)
