### ISSUE TITLE
Resolver referência ao caso da Sra,  Marietje Schaake

### ISSUE THREAD

**Issue by nmota** [marado/mp#24]
Há uma indicação de referência sob a forma de "[1]" incompleta que é preciso ou adicionar o link correcto ou remover. 
Está na secção dos filtros automáticos do artigo 13º.

**Comment by marado** [comment]
É para tirar

**Comment by EdSantos754** [comment]
Retirar a referencia e linkar directamente no texto o seguinte link, sff.
https://www.marietjeschaake.eu/en/when-youtube-took-down-my-video
