### ISSUE TITLE
art. 3: texto de detalhe

### ISSUE THREAD

**Issue by marado** [marado/mp#38]
Ainda não temos texto de detalhe para o Art. 3 (TDM).
É lapso, ou ainda não está escrito?

**Comment by EdSantos754** [comment]
> A prospeção de texto e dados refere-se ao processo de ler enormes quantidades de texto ou dados, através de uma máquina (por exemplo, um computador), extrair informação e encontrar padrões e tendências, que permita tirar conclusões. Para realizar esta leitura é, muitas vezes, necessário fazer cópias, sem as quais não é possível fazer TDM.
> No artigo referente à prospecção de textos e dados (TDM), é proposta uma excepção obrigatória para permitir a análise automatizada de grandes quantidades de dados, mas apenas para fins de investigação. O objectivo é permitir a organizações de investigação usarem ferramentas de TDM em material com direitos de autor acedidos legalmente sem necessidade de pagamento ou autorização prévia por parte dos autores ou detentores de direitos.
> 
> Infelizmente, isto  exclui todos os outros actores dos benefícios da excepção, tal como unidades de I&D de companhias, startups, jornalistas, cidadãos, organizações da sociedade civil, instituições de património cultural e organismos públicos. Todas as entidades não consideradas como sendo de investigação terão de negociar uma licença. Isto seria incrivelmente difícil - ou mesmo impossível - considerando que TDM incorpora milhares de artigos ou datasets por tópico.
> 
> Hoje em dia o conhecimento é gerado não só em Universidades, mas também em empresas e instituições públicas, e por cidadãos a contribuir cada vez mais para o avanço da ciência e da inovação. A automatização do uso de algoritmos é essencial para criar sentido a partir de grandes quantidades de dados. Desde serviços de informação sobre obras culturais até provas científicas sobre tratamentos médicos, uma excepção que permita universalmente o uso de TDM pode ajudar a criar soluções a problemas dos Portugueses, sejam eles pequenos ou grandes problemas.
> As técnicas de TDM são ainda imprescindíveis na fiscalização e transparência da administração pública tão importante para os cidadãos. A enorme quantidade de informação produzida e disponibilizada pelos governos e outras entidades públicas só pode ser verificada e analisada através da prospecção de texto e dados. Mas nem toda a informação criada pelas entidades públicas está em domínio público.
> 
> Ao excluir a maioria dos potenciais beneficiários, a excepção não dá resposta às enormes oportunidades à descoberta científica e à inovação. Como resultado, aqueles que quiserem criar um modelo de negócio com base em TDM irão fazê-lo fora da Europa, onde tais limitações não restringem a sua actividade - em detrimento das economias e do trabalho Europeus, incluindo o Português.
> 
> A Europa precisa de uma excepção obrigatória de TDM para todos os utilizadores e para todas as finalidades. A melhor forma de o conseguir é alargando o âmbito desta excepção na proposta de directiva.

**Comment by EdSantos754** [comment]
@marado, podes colocar tu este, sff?
