### ISSUE TITLE
[Discussão] Restrição Liberdade Expressão (texto final?)

### ISSUE THREAD

**Issue by EdSantos754** [marado/mp#41]
Estou a rever texto a texto. Vamos fazer um issue por secção. Proponham modificações e/ou dêem o vosso ok.

Alterações propostas a bold:

> É uma restrição desproporcional da liberdade de expressão dos cidadãos
> 
> No mundo digital em que vivemos, a liberdade de expressão conhece grande eco online, o que dá aos operadores privados nesse ambiente um poder imenso (e responsabilidade), a que estamos mais habituados a associar a poderes estatais.
> 
> Limitar a liberdade de expressão, ao filtrar os conteúdos que os utilizadores entendam partilhar, é uma questão de primeira importância. É uma questão de direitos fundamentais.
> 
> Saberá o Sr. Eurodeputado melhor do que nós, por certo, que a restrição de um direito fundamental deve seguir critérios de proporcionalidade, apenas sendo admissível tal restrição quando estritamente necessária e adequada ao fim a alcançar.
> 
> Não menosprezamos os desafios que os autores enfrentam na Era Digital, mas consideramos que é manifestamente desproporcional submeter todos os conteúdos enviados pelos utilizadores a filtros de qualquer tipo.
> 
> Consideramos que a liberdade de expressão dos cidadãos deve estar acima dos - perfeitamente legítimos - interesses económicos dos detentores de direitos. Principalmente quando a esmagadora maioria dos conteúdos enviados para a rede não atinge os interesses económicos dos detentores de direitos. **[APAGAR]Mas mesmo quando são utilizados conteúdos protegidos por direito de autor, outras questões pertinentes se levantam.[/APAGAR] Por favor não permita que a voz dos cidadãos no espaço público digital seja submetida a filtros de qualquer tipo.**

**Comment by paulasimoes** [comment]
@EdSantos754 achas que ficaria melhor nesta frase:
"submeter todos os conteúdos enviados pelos utilizadores a filtros de qualquer tipo."
algo do tipo
"submeter todos os conteúdos enviados pelos utilizadores a uma monitorização prévia."
?
também concordo com a frase para apagar.
de resto acho bem.

**Comment by EdSantos754** [comment]
Siga

> É uma restrição desproporcional da liberdade de expressão dos cidadãos
> 
> No mundo digital em que vivemos, a liberdade de expressão conhece grande eco online, o que dá aos operadores privados nesse ambiente um poder imenso (e responsabilidade), a que estamos mais habituados a associar a poderes estatais.
> 
> Limitar a liberdade de expressão, ao filtrar os conteúdos que os utilizadores entendam partilhar, é uma questão de primeira importância. É uma questão de direitos fundamentais.
> 
> Saberá o Sr. Eurodeputado melhor do que nós, por certo, que a restrição de um direito fundamental deve seguir critérios de proporcionalidade, apenas sendo admissível tal restrição quando estritamente necessária e adequada ao fim a alcançar.
> 
> Não menosprezamos os desafios que os autores enfrentam na Era Digital, mas consideramos que é manifestamente desproporcional submeter todos os conteúdos enviados pelos utilizadores a uma monitorização prévia.
> 
> Consideramos que a liberdade de expressão dos cidadãos deve estar acima dos - perfeitamente legítimos - interesses económicos dos detentores de direitos. Principalmente quando a esmagadora maioria dos conteúdos enviados para a rede não atinge os interesses económicos dos detentores de direitos. Por favor não permita que a voz dos cidadãos no espaço público digital seja submetida a filtros de qualquer tipo.
