### ISSUE TITLE
[Discussão] Plataformas não são juízes (texto final?)

### ISSUE THREAD

**Issue by EdSantos754** [marado/mp#42]
Estou a rever texto a texto. Vamos fazer um issue por secção. Proponham modificações e/ou dêem o vosso ok.

Alterações propostas a bold:

> Actualmente as plataformas **que alojam conteúdo enviado por utilizadores** já podem ser responsabilizadas **pelos** conteúdos que **alojam** desde que, sempre que tiverem conhecimento ou sejam notificadas da presença de conteúdos ilegítimos, não procedam diligentemente e rapidamente no sentido de remover tais conteúdos.
> 
> **Este regime, que está em vigor**, ainda que **não seja isento de problemas (*), ainda assim revela** uma certa ponderação dos interesses em jogo.
> 
> Pelo contrário, o regime agora proposto, pretende responsabilizar as plataformas, que são apenas intermediários, tal como se fossem elas próprias - e não os seus utilizadores - a enviar os conteúdos. Na prática, será de esperar que essas empresas defendam antes de mais os seus legítimos interesses económicos e comerciais.
> 
> Colocadas perante a possibilidade de serem responsabilizadas pelos conteúdos que os utilizadores enviam, irão agir de forma preventiva e conservadora, censurando primeiro e perguntando depois.
> 
> Em caso de mínima dúvida, as empresas colocar-se-ão sempre do lado dos detentores de direitos, não do lado da liberdade de expressão dos cidadãos, dada a assimetria de poder existente.
> 
> Estas empresas não vão ser os novos juízes das liberdades. Tais empresas:
> 
>     não têm qualquer legitimidade ou competência para desempenhar esse papel;
>     não têm também qualquer tipo de incentivo para o fazerem de forma imparcial;
>     nem sequer estão interessadas em fazê-lo.
> 
> Nestas circunstâncias, ter razão, de pouco valerá a um mero utilizador.
> 
> O regime actual já responsabiliza as plataformas pelos conteúdos enviados pelos utilizadores. Não se justifica um agravamento deste regime.

(*)- colocar este link: https://www.eff.org/takedowns

**Comment by EdSantos754** [comment]
Mudei apenas uma parte pequena: "Este regime actualmente em vigor, ainda que..."

**Comment by marado** [comment]
Merged. Podemos fechar o issue?

**Comment by EdSantos754** [comment]
sim, vai fechando sff.
