### ISSUE TITLE
[Discussão] Utilizadores culpados até prova em contrário (texto final?) 

### ISSUE THREAD

**Issue by EdSantos754** [marado/mp#43]
Estou a rever texto a texto. Vamos fazer um issue por secção. Proponham modificações e/ou dêem o vosso ok.

Alterações propostas a bold:

> 
> Além de impedir utilizações livres perfeitamente legítimas e de tornar as plataformas nos novos juízes das liberdades, o regime proposto torna os utilizadores culpados até prova em contrário. Nos casos em que um conteúdo enviado pelo utilizador seja apanhado no filtro, a quem poderá aquele recorrer?
> 
> Nem os detentores de direitos nem as plataformas serão parte imparcial na análise do caso.
> 
> E qual será o regime legal aplicável, dado que as excepções e limitações do direito de autor, por serem opcionais para os Estados-Membros, são diferentes em cada Estado-Membro?
> 
> Poderia um cidadão Português usar livremente do seu direito de “citação para crítica”, previsto pela lei Portuguesa, para efectuar uma crítica a uma obra de Slavoj Žižek numa dessas plataformas, quando a lei Eslovena não contempla tal excepção?
> 
> Os detentores de direitos defendem a necessidade dos filtros de upload pois dizem que o ónus de identificar conteúdo ilegítimo lhes é demasiado oneroso. No entanto, acham que é razoável que os cidadãos tenham de recorrer aos tribunais, como está previsto na proposta actual, a fim de recorrer de uma “filtragem” errada.
> 
> **O Youtube, sozinho, conta com cerca de 300 horas de novo conteúdo a cada minuto que passa. Se alguém quisesse assistir a todos os vídeos que foram enviados para o Youtube durante uma determinada hora, necessitaria de ficar mais de quatro anos a assistir a vídeos, 12 horas por dia, para os conseguir ver a todos.**
> 
> **Nesta escala colossal, mesmo que um filtro tenha uma margem de erro reduzida em termos percentuais, irá sempre resultar num número enorme de falhas e falsos positivos.** 
> 
> **E se as plataformas não são juízes de direito e não têm qualquer incentivo para decidir de forma imparcial, será então razoável fazer pender sobre os cidadãos o ónus de recorrer aos tribunais por causa de vídeos mal apagados? Claro que a maioria não o fará. Mas mesmo concedendo que muitos até o façam, vamos inundar os nossos tribunais de casos destes?**
> 
> Depois das “bagatelas penais”, teremos as “bagatelas autorais”?

**Comment by paulasimoes** [comment]
acho muito bem, sugeria que no final onde se lê "vídeos mal apagados" se mudasse para "vídeos erradamente apagados" ou "vídeos erradamente removidos".

**Comment by EdSantos754** [comment]
Siga

> Além de impedir utilizações livres perfeitamente legítimas e de tornar as plataformas nos novos juízes das liberdades, o regime proposto torna os utilizadores culpados até prova em contrário. Nos casos em que um conteúdo enviado pelo utilizador seja apanhado no filtro, a quem poderá aquele recorrer?
> 
> Nem os detentores de direitos nem as plataformas serão parte imparcial na análise do caso.
> 
> E qual será o regime legal aplicável, dado que as excepções e limitações do direito de autor, por serem opcionais para os Estados-Membros, são diferentes em cada Estado-Membro?
> 
> Poderia um cidadão Português usar livremente do seu direito de “citação para crítica”, previsto pela lei Portuguesa, para efectuar uma crítica a uma obra de Slavoj Žižek numa dessas plataformas, quando a lei Eslovena não contempla tal excepção?
> 
> Os detentores de direitos defendem a necessidade dos filtros de upload pois dizem que o ónus de identificar conteúdo ilegítimo lhes é demasiado oneroso. No entanto, acham que é razoável que os cidadãos tenham de recorrer aos tribunais, como está previsto na proposta actual, a fim de recorrer de uma “filtragem” errada.
> 
> O Youtube, sozinho, conta com cerca de 300 horas de novo conteúdo a cada minuto que passa. Se alguém quisesse assistir a todos os vídeos que foram enviados para o Youtube durante uma determinada hora, necessitaria de ficar mais de quatro anos a assistir a vídeos, 12 horas por dia, para os conseguir ver a todos.
> 
> Nesta escala colossal, mesmo que um filtro tenha uma margem de erro reduzida em termos percentuais, irá sempre resultar num número enorme de falhas e falsos positivos.
> 
> E se as plataformas não são juízes de direito e não têm qualquer incentivo para decidir de forma imparcial, será então razoável fazer pender sobre os cidadãos o ónus de recorrer aos tribunais por causa de vídeos erradamente removidos? Claro que a maioria não o fará. Mas mesmo concedendo que muitos até o façam, vamos inundar os nossos tribunais de casos destes?
> 
> Depois das “bagatelas penais”, teremos as “bagatelas autorais”?
