### ISSUE TITLE
[Discussão] Jurisprudencia do TJUE (texto final?) 

### ISSUE THREAD

**Issue by EdSantos754** [marado/mp#44]
Estou a rever texto a texto. Vamos fazer um issue por secção. Proponham modificações e/ou dêem o vosso ok.

> O Tribunal de Justiça da União Europeia já se pronunciou precisamente contra uma obrigatoriedade de monitorização generalizada das plataformas sobre o conteúdo enviado pelos utilizadores.
> 
> Tal monitorização não respeita os direitos fundamentais dos cidadãos, previstos na Carta dos Direitos Fundamentais da União Europeia.
> 
> A obrigação de filtrar todos os conteúdos enviados pelos utilizadores para uma plataforma é precisamente uma obrigação de monitorização geral de conteúdos.

**Incompleto. Precisa de melhorias. Voltarei a ele.**

**Comment by paulasimoes** [comment]
Sugestão: (não sei se vale a pena dissecar o estudo (?)), talvez seja importante citar as directivas especificamente.

Nas duas decisões, o Tribunal de Justiça da União Europeia concluiu que as cinco directivas:

- 2000/31/CE do Parlamento Europeu e do Conselho, de 8 de Junho de 2000, relativa a certos aspectos legais dos serviços da sociedade de informação, em especial do comércio electrónico, no mercado interno («Directiva sobre o comércio electrónico»);

- 2001/29/CE do Parlamento Europeu e do Conselho, de 22 de Maio de 2001, relativa à harmonização de certos aspectos do direito de autor e dos direitos conexos na sociedade da informação;

- 2004/48/CE do Parlamento Europeu e do Conselho, de 29 de Abril de 2004, relativa ao respeito dos direitos de propriedade intelectual;

- 95/46/CE do Parlamento Europeu e do Conselho, de 24 de Outubro de 1995, relativa à protecção das pessoas singulares no que diz respeito ao tratamento de dados pessoais e à livre circulação desses dados; e

- 2002/58/CE do Parlamento Europeu e do Conselho, de 12 de Julho de 2002, relativa ao tratamento de dados pessoais e à protecção da privacidade no sector das comunicações electrónicas (Directiva relativa à privacidade e às comunicações electrónicas);

devem ser interpretadas no sentido de que se opõem a um sistema de filtragem com carácter preventivo.

O [estudo](https://juliareda.eu/wp-content/uploads/2017/03/angelopoulos_platforms_copyright_study.pdf) de Christina Angelopoulos, do Centre for Intellectual Property and Information Law (CIPIL) da Universidade de Cambridge, identifica ainda vários problemas legais fundamentais no artigo proposto, efectuando uma análise rigorosa e exaustiva do artigo 13º, proposto pela Comissão Europeia.

**Comment by EdSantos754** [comment]
Não creio, Paula. O importante é a decisão, não as directivas em que ela se baseia. Perdemos a atenção de quem lê, com a enumeração de tanta lei.

Talvez assim?

> O Tribunal de Justiça da União Europeia já se pronunciou [1] precisamente contra um sistema de filtragem com carácter preventivo, afirmando explicitamente que inexiste uma obrigação de vigilância geral das plataformas sobre os conteúdos.
> 
> Tal obrigação de vigilância geral _[general monitoring]_ não respeita os direitos fundamentais dos cidadãos, previstos na Carta dos Direitos Fundamentais da União Europeia. Entendeu o Tribunal, que além de não cumprir o artigo 3.°, n.° 1, da Directiva 2004/48, que determina que as medidas para assegurar o respeito dos direitos de propriedade intelectual não devem ser desnecessariamente complexas ou onerosas, estará também em causa os artigos 8.° e 11.° da Carta dos Direitos Fundamentais da União Europeia, isto é, o direito à protecção dos dados pessoais e a liberdade de receber ou de enviar informações.
> 
> Uma obrigação de filtrar todos os conteúdos enviados pelos utilizadores para uma plataforma é precisamente uma obrigação de vigilância geral e activa de conteúdos.

1- http://eur-lex.europa.eu/legal-content/PT/TXT/?uri=CELEX%3A62010CJ0070

**Comment by marado** [comment]
Assim se descobre a existência do verbo inexistir... Ainda assim, substituiria "inexiste" por "não existe" :-)

**Comment by EdSantos754** [comment]
Mariquices do juridiquês. É como o inconseguir :P

> O Tribunal de Justiça da União Europeia já se pronunciou [1] precisamente contra um sistema de filtragem com carácter preventivo, afirmando explicitamente que não existe uma obrigação de vigilância geral das plataformas sobre os conteúdos.
> 
> Tal obrigação de vigilância geral _[general monitoring]_ não respeita os direitos fundamentais dos cidadãos, previstos na Carta dos Direitos Fundamentais da União Europeia. Entendeu o Tribunal, que além de não cumprir o artigo 3.°, n.° 1, da Directiva 2004/48, que determina que as medidas para assegurar o respeito dos direitos de propriedade intelectual não devem ser desnecessariamente complexas ou onerosas, estará também em causa os artigos 8.° e 11.° da Carta dos Direitos Fundamentais da União Europeia, isto é, o direito à protecção dos dados pessoais e a liberdade de receber ou de enviar informações.
> 
> Uma obrigação de filtrar todos os conteúdos enviados pelos utilizadores para uma plataforma é precisamente uma obrigação de vigilância geral e activa de conteúdos.

1- http://eur-lex.europa.eu/legal-content/PT/TXT/?uri=CELEX%3A62010CJ0070
