### ISSUE TITLE
[Discussão] Art 11º (texto final?)

### ISSUE THREAD

**Issue by EdSantos754** [marado/mp#48]
Estou a rever texto a texto. Vamos fazer um issue por secção. Proponham modificações e/ou dêem o vosso ok.

Original:

> Art. 11º: A "taxa" do link
> 
> Este artigo introduz um novo direito conexo a favor dos editores de imprensa, em relação aos conteúdos jornalísticos por estes publicados - além do direito de autor de que tais obras já beneficiam. Tal direito conexo permitirá às publicações de imprensa impedir os cidadãos de partilharem links para notícias ou obrigar as plataformas a negociarem uma licença. Durante 20 anos. 
> 
> Como assim, pagar por linkar?
>
> O que está em causa?
> 
> Está ainda por definir qual exactamente a utilização que será objecto da obrigatoriedade de adquirir uma licença. Propostas mais extremas defendem que a partilha de um link é suficiente para obrigar ao pagamento, outras defendem que tal direito deverá incidir apenas quando seja partilhado um link acompanhado do título da notícia do texto (snippet), e outras ainda discutem qual o número de palavras, num título de notícia, a partir do qual deve existir obrigação de adquirir a licença. Por outro lado, pode acontecer que as publicações de imprensa possam decidir simplesmente não emitir licenças para determinadas plataformas, proibindo aí a partilha de links para notícias.
> 
> Recordamos que, dada a ausência de criatividade de um título de notícia - geralmente uma descrição factual - e também por motivos óbvios de interesse público e praticabilidade, um comum título de notícia não é, por norma, objecto de direito de autor. Mas seria sujeito a este direito conexo.
> Que impactos pode ter esta medida?
> 
> Esta proposta terá uma série de impactos negativos na Internet livre e aberta que conhecemos e usamos todos os dias:
> 
>     
> - Esta medida já foi tentada em Espanha em na Alemanha, com resultados desastrosos. Na Alemanha, a intervenção do legislador levou a que a Google deixasse de utilizar os "snippets" no seu serviço de Google News. Como as pessoas não clicam tanto em links que não são acompanhados do devido contexto, o tráfego enviado para os sites dos editores de imprensa caiu a pique, pelo que estes rapidamente negociaram com a Google a concessão de uma licença gratuita, que permitisse restaurar a situação anterior à mudança legislativa. Na prática, portanto, esta medida veio apenas reforçar a posição monopolística da Google, que utilizou o seu poder de mercado para conseguir uma licença gratuita que não foi concedida de igual forma aos seus concorrentes. A lei tornou-se portanto numa barreira à concorrência à Google. Posteriormente, em Espanha, o legislador aprovou uma lei similar, mas proibindo a emissão de licenças gratuitas. A Google fechou então o seu serviço de notícias, ficando os editores de imprensa todo o tráfego que vinha de lá, e que tinha um considerável peso no tráfego global recebido pelos seus websites.
> - Esta medida coloca em causa o direito de informar e o direito de ser informado. Os cidadãos necessitam de poder partilhar links para informação de forma livre, e necessitem de plataformas que facilitem a partilha de informação. A Internet é um sistema descentralizado de informação, motores de busca e outros agregadores são essenciais para levar a informação ao público.
> - Os editores de imprensa beneficiam do tráfego enviado pelas plataformas, para venderem a publicidade que têm nos respectivos sites e gerar receitas. Esta relação é benéfica para as duas partes. Quanto mais visitas tiverem aos seus sites, mais publicidade e mais cara conseguem vender. Se existe um "value gap", é devido ao papel crucial desempenhado por motores de busca e redes sociais na Internet, que também lhes permite gerar receitas avultadas - com ou sem as ligações para os editores de imprensa. Por outras palavras, ao alegado "value gap" falta uma relação de causa-efeito, que possa justificar intervenção do legislador.
> - Editores de imprensa pequenos, como os locais ou regionais, seriam os mais directamente afectados - quando são os que menos voz têm na matéria. Esta medida iria apenas beneficiar os grandes grupos de comunicação social, agravando a já complicada situação de concentração da comunicação social em poucos grupos económicos.
> - Iria causar um efeito nefasto na competição e inovação: As start-ups e pequenas empresas europeias não têm capacidade financeira para pagar licenças para links ou "snippets", pelo que deixariam de tentar competir e criar alternativas ao Google e Facebook, ou, para o fazer, teriam de se deslocalizar para fora da União Europeia.
> - Numa altura em que tanta atenção é dada às "fake news" e aos desafios que estas colocam à nossa sociedade, aprovar uma medida que desincentiva a partilha de conteúdos jornalísticos legítimos e fidedignos parece ser uma receita para o desastre. As pessoas não vão sair da Web, nem vão deixar de partilhar conteúdos. Passarão a partilhar os conteúdos que as deixarem partilhar. Quem produz “fake news” não quer saber de direitos de autor, nem de direitos conexos, pois estes servem sobretudo para restringir o acesso. Quem produz “fake news” quer que estas se espalhem o mais rapidamente possível. Se deixarmos de ter “notícias verdadeiras” a circular na Web para contrabalançar as “fake news” é de esperar que o impacto destas aumente. Se notarmos que as “fake news” são dirigidas a questões políticas, podemos assim concluir que o artigo 11º é extremamente perigoso para o funcionamento da nossa democracia.
> - Consagrar uma excepção para "utilização não comercial" não é suficiente, e é de difícil execução, porque a maior parte dos links são partilhados sem fins lucrativos, mas em plataformas que têm em si fins lucrativos.
> - Não há necessidade de criar este direito conexo ao direito de autor. Os editores de imprensa alegam que o objectivo desta medida é fazer cumprir, na prática, o direito de autor. Para tal seria suficiente a consagração de uma presunção legal que permita aos editores de imprensa agir judicialmente, em nome dos seus jornalistas, contra eventuais infracções.
> 
> Esta proposta deve ser rejeitada.

**Comment by EdSantos754** [comment]
Bem, este art 11º é complicado. Acho que há aqui várias frases problemáticas. Os textos que cito abaixo já cito com pequenas propostas de alteração/melhorias, e depois em baixo discuto/proponho outras (mais discutíveis).

> **Este artigo introduz um novo direito conexo a favor dos editores de imprensa, em relação aos conteúdos jornalísticos por estes publicados - além do direito de autor de que tais obras já beneficiam. Tal direito conexo permitirá às publicações de imprensa impedir os cidadãos de partilharem links para notícias ou obrigar as plataformas a negociarem uma licença. Terá a duração de 20 anos.** 

impedir cidadãos de partilhar links? Quanto muito conclui-se isso no trecho seguinte. Uma consequência, não o objecto do direito, i.e., não entraria logo com isto. Suavizaria a frase, algo tipo:
"Tal direito conexo obrigará as plataformas a negociar uma licença para que os cidadãos possam partilhar links tal como o fazem hoje em dia, em último caso impedindo-os de realizar tal partilha."

> **Não é de todo claro que tipo de utilização será objecto da obrigatoriedade de adquirir uma licença. Interpretações mais extremas defendem que a partilha de um link é suficiente para obrigar ao pagamento, outras defendem que tal direito deverá incidir apenas quando seja partilhado um link acompanhado do título da notícia e texto (snippet), e outras ainda discutem qual o número de palavras, num título de notícia, a partir do qual deve existir obrigação de adquirir a licença. Por outro lado, pode acontecer que as publicações de imprensa possam decidir simplesmente não emitir licenças para determinadas plataformas, proibindo aí a partilha de links para notícias.**

Todas estas opções são mesmo defendidas? Conseguimos colocar um link para cada uma delas? 
Adicionaria aqui link para o video do depoimento do teu "amigo", Paula.


     
> - Esta medida já foi tentada em Espanha em na Alemanha, com resultados desastrosos. Na Alemanha, a intervenção do legislador levou a que a Google deixasse de utilizar os "snippets" no seu serviço de Google News. Como as pessoas não clicam tanto em links que não são acompanhados do devido contexto, o tráfego enviado para os sites dos editores de imprensa caiu a pique, pelo que estes rapidamente negociaram com a Google a concessão de uma licença gratuita, que permitisse restaurar a situação anterior à mudança legislativa. Na prática, portanto, esta medida veio apenas reforçar a posição **monopolista** da Google, que utilizou o seu poder de mercado para conseguir uma licença gratuita que não foi concedida de igual forma aos seus concorrentes. A lei tornou-se portanto numa barreira à concorrência à Google. Posteriormente, em Espanha, o legislador aprovou uma lei similar, mas proibindo a emissão de licenças gratuitas. A Google fechou então o seu serviço de notícias, ficando os editores de imprensa todo o tráfego que vinha de lá, e que tinha um considerável peso no tráfego global recebido pelos seus websites.

>  - Os editores de imprensa beneficiam do tráfego enviado pelas plataformas, para venderem a publicidade que têm nos respectivos sites e gerar receitas. Esta relação é benéfica para as duas partes. Quanto mais visitas tiverem aos seus sites, mais publicidade e mais cara conseguem vender. Se existe um "value gap", é devido ao papel crucial desempenhado por motores de busca e redes sociais na Internet, que também lhes permite gerar receitas avultadas - com ou sem as ligações para os editores de imprensa. **Por outras palavras, ao alegado "value gap" falta uma relação de causa-efeito, que pudesse justificar intervenção do legislador: "A ideia de que a criação de valor deva levar automaticamente ao um pagamento não tem base científica" (Copyright Reform: Open Letter from European Research Centre] http://www.create.ac.uk/wp-content/uploads/2017/02/OpenLetter_EU_Copyright_Reform_24_02_2017.pdf**

> - Não há necessidade de criar este direito conexo ao direito de autor. Os editores de imprensa alegam que o objectivo desta medida é fazer cumprir, na prática, o direito de autor. Para tal seria suficiente a consagração de uma presunção legal que permita aos editores de imprensa agir judicialmente, em nome dos seus jornalistas, contra eventuais **infracções ao direito de autor.**
@

**Comment by paulasimoes** [comment]
> Se existe um "value gap"

Não vejo ninguém a referir o value gap no artigo 11º, mas sim no artigo 13º. 

vou tentar reformular o texto

**Comment by paulasimoes** [comment]
@EdSantos754 reformulei o texto, para ser mais rigoroso, eliminei a proibição dos links, e coloquei referências para quase todos os pontos que podem ser discutidos. acrescentei ponto sobre as fake news. removi a cena do value gap, porque este tem sido referido no contexto do artigo 13º. acrescentei info sobre os acordos que a google tem feito com os editores.
de qualquer forma, altera como achares bem:


Este artigo introduz um novo direito conexo a favor dos editores de publicações de imprensa, em relação aos conteúdos por estes publicados - além do direito de autor de que tais obras já beneficiam. Tal direito conexo permitirá às publicações de imprensa impedir a partilha de excertos de notícias ou obrigar as plataformas a negociarem uma licença para essa partilha ser permitida. Terá a duração de 20 anos.



Não é de todo claro que tipo de utilização será objecto da obrigatoriedade de adquirir uma licença. Algumas interpretações defendem que a menção ao nome da publicação (1) numa partilha é suficiente para obrigar ao pagamento. Apesar da proposta referir nos considerandos que a lei não se aplica aos links, por estes não constituirem uma comunicação ao público, há quem questione se também será assim no caso das hiperligações que incluem o título da notícia no próprio URL (2). Por outro lado, se uma das propostas do artigo 13º que considera que as plataformas cometem um acto de comunicação ao público (3) for aprovada, pode ter influência no artigo 11º, e atingir os próprios links (que são um tipo de conteúdos partilhados nessas plataformas). 
Certo é que a partilha dos chamados snippets (conjunto de título, excerto da notícia e/ou nome da publicação) terá sempre de ser objecto de uma licença para ser permitida (4).
Por outro lado, pode acontecer que as publicações de imprensa possam decidir simplesmente não emitir licenças para determinadas plataformas, proibindo a partilha de excertos de notícias (5).

Esta medida já foi tentada em Espanha e na Alemanha, com resultados desastrosos. Na Alemanha, a intervenção do legislador levou a que a Google deixasse de utilizar os "snippets" no seu serviço de Google News. Como as pessoas não clicam tanto em links que não são acompanhados do devido contexto, o tráfego enviado para os sites dos editores de imprensa caiu a pique, pelo que estes rapidamente negociaram com a Google a concessão de uma licença gratuita, que permitisse restaurar a situação anterior à mudança legislativa. Na prática, portanto, esta medida veio apenas reforçar a posição monopolista da Google, que utilizou o seu poder de mercado para conseguir uma licença gratuita que não foi concedida de igual forma aos seus concorrentes. A lei tornou-se portanto numa barreira à concorrência à Google. Posteriormente, em Espanha, o legislador aprovou uma lei similar, mas proibindo a emissão de licenças gratuitas. A Google fechou então o seu serviço de notícias, ficando os editores de imprensa sem o tráfego que vinha de lá, e que tinha um considerável peso no tráfego global recebido pelos seus websites. Apesar desta lei ter como argumento a utilização de excertos de notícias pelo Google News será quase impossível convencer a Google a pagar pela utilização desses excertos, uma vez que a empresa não tem publicidade no Google News (6) e portanto não vai pagar por um serviço com o qual não faz dinheiro.

Os editores de imprensa beneficiam do tráfego enviado pelas plataformas, para venderem a publicidade que têm nos respectivos sites e gerar receitas. Esta relação é benéfica para as duas partes. Quanto mais visitas tiverem aos seus sites, mais publicidade e mais cara conseguem vender. E se é certo que os agregadores passaram a ficar com parte dessa publicidade, por terem encontrado formas melhores e mais apelativas de transmitir informação, esta lei não vai resolver esse problema. Em vez de criar uma lei para a Google, que vai impactar plataformas mais pequenas ou inovadoras, prejudicando o acesso dos cidadãos à informação, seria melhor fomentar acordos entre a Google e os editores de publicações de imprensa, como aconteceu na Bélgica (7), em França com o French Innovation Fund (8) ou através do Digital News Innovation Fund (9), que continua a apoiar os editores de publicações de imprensa, e do qual já beneficiaram no passado publicações como a Lusa e o jornal Público (10).

Não há necessidade de criar este direito conexo ao direito de autor. Os editores de imprensa alegam que o objectivo desta medida é fazer cumprir, na prática, o direito de autor. Para tal seria suficiente a consagração de uma presunção legal que permita aos editores de imprensa agir judicialmente, em nome dos seus jornalistas, contra eventuais infracções ao direito de autor. 

Por fim, mesmo no melhor cenário possível haverá sempre uma redução na circulação das notícias de jornalismo profissional (como assegura o advogado Thomas Hopper este é um direito de proibição). Haverá sempre publicações que não estão disponíveis para emitir licenças, haverá sempre agregadores que não poderão pagar licenças e haverá, como aconteceu em Espanha e na Alemanha, agregadores que não quererão pagar licenças.
A uma redução da circulação de notícias de jornalismo profissional corresponderá um aumento da circulação das chamadas “fake news”, uma vez que as pessoas não vão sair da Web, nem vão deixar de partilhar conteúdos. Os utilizadores partilham os conteúdos que os deixarem partilhar.
Há uns meses, o Facebook anunciou uma mudança no seu algoritmo que passaria a dar preferência a conteúdos de perfis (pessoas) em detrimento de conteúdos partilhados por páginas (jornais, revistas, marcas, e outras pessoas colectivas). A Folha de São Paulo fez algumas medições das interações dos utilizadores com os conteúdos de publicações de imprensa e publicações de "fake news", entre Outubro de 2007 e Janeiro de 2018, observando naquele período uma diminuição da taxa média de interacções de 17% dos utilizadores com as notícias de jornalismo profissional, ao mesmo tempo que observou um aumento de 61,6% na taxa média de interacções dos utilizadores com “fake news” (11). É expectável que qualquer sistema que faça diminuir a circulação de notícias de jornalismo profissional, faça também aumentar a circulação de “fake news”, seja um algoritmo no Facebook ou uma lei deste tipo. 


(1) [https://youtu.be/j\_IRPt8iLuo?t=27m43s]
(2) [https://youtu.be/j\_IRPt8iLuo?t=34m5s]
(3) [https://juliareda.eu/wp-content/uploads/2018/02/20180221-Draft-CA-on-Article-13\_v1.pdf]
(4) [https://youtu.be/\_IAXuIARfFM?t=8s]
(5) [https://youtu.be/\_IAXuIARfFM?t=1m4s]
(6) [https://news.google.com]
(7) [https://europe.googleblog.com/2012/12/partnering-with-belgian-news-publishers.html]
(8) [https://blog.google/topics/google-europe/knowledge-for-everyone/]
(9) [https://newsinitiative.withgoogle.com/dnifund/]
(10) [http://www.twipemobile.com/projects-funded-by-google-digital-news-initiative-in-the-first-round/]
(11) [https://www1.folha.uol.com.br/poder/2018/02/fake-news-ganha-espaco-no-facebook-e-jornalismo-profissional-perde.shtml]

**Comment by EdSantos754** [comment]
Muito fixe, Siga!

**Comment by EdSantos754** [comment]
```
<p>Este artigo introduz um novo direito conexo a favor dos editores de publicações de imprensa, em relação aos conteúdos por estes publicados - além do direito de autor de que tais obras já beneficiam. Tal direito conexo permitirá às publicações de imprensa impedir a partilha de excertos de notícias ou obrigar as plataformas a negociarem uma licença para essa partilha ser permitida. Terá a duração de 20 anos.</p>

<p>Não é de todo claro que tipo de utilização será objecto da obrigatoriedade de adquirir uma licença. Algumas interpretações defendem que <a href="https://youtu.be/j_IRPt8iLuo?t=27m43s">a menção ao nome da publicaçãot</a> numa partilha é suficiente para obrigar ao pagamento. Apesar da proposta referir nos considerandos que a lei não se aplica aos links, por estes não constituirem uma comunicação ao público, há quem questione se também será assim  <a href="https://youtu.be/j_IRPt8iLuo?t=34m5s">no caso das hiperligações que incluem o título da notícia no próprio URL</a>). Por outro lado, se uma das propostas do artigo 13º que considera que <a href="https://juliareda.eu/wp-content/uploads/2018/02/20180221-Draft-CA-on-Article-13_v1.pdf">as  plataformas cometem um acto de comunicação ao público </a> for aprovada, pode ter influência no artigo 11º, e atingir os próprios links (que são um tipo de conteúdos partilhados nessas plataformas).
Certo é que a partilha dos chamados snippets (conjunto de título, excerto da notícia e/ou nome da publicação) <a href="https://youtu.be/_IAXuIARfFM?t=8s">terá sempre de ser objecto de uma licença para ser permitida</a>.
Por outro lado, pode acontecer que as publicações de imprensa possam decidir simplesmente não emitir licenças para determinadas plataformas, <a href="https://youtu.be/_IAXuIARfFM?1m4s">proibindo a partilha de excertos de notícias.</a></p>

<p>Esta medida já foi tentada em Espanha e na Alemanha, com resultados desastrosos. Na Alemanha, a intervenção do legislador levou a que a Google deixasse de utilizar os "snippets" no seu serviço de Google News. Como as pessoas não clicam tanto em links que não são acompanhados do devido contexto, o tráfego enviado para os sites dos editores de imprensa caiu a pique, pelo que estes rapidamente negociaram com a Google a concessão de uma licença gratuita, que permitisse restaurar a situação anterior à mudança legislativa. Na prática, portanto, esta medida veio apenas reforçar a posição monopolista da Google, que utilizou o seu poder de mercado para conseguir uma licença gratuita que não foi concedida de igual forma aos seus concorrentes. A lei tornou-se portanto numa barreira à concorrência à Google. Posteriormente, em Espanha, o legislador aprovou uma lei similar, mas proibindo a emissão de licenças gratuitas. A Google fechou então o seu serviço de notícias, ficando os editores de imprensa sem o tráfego que vinha de lá, e que tinha um considerável peso no tráfego global recebido pelos seus websites. Apesar desta lei ter como argumento a utilização de excertos de notícias pelo Google News será quase impossível convencer a Google a pagar pela utilização desses excertos, uma vez que a empresa não tem publicidade no <a href="https://news.google.com">Google News</a> e portanto não vai pagar por um serviço com o qual não faz dinheiro.</p>

<p>Os editores de imprensa beneficiam do tráfego enviado pelas plataformas, para venderem a publicidade que têm nos respectivos sites e gerar receitas. Esta relação é benéfica para as duas partes. Quanto mais visitas tiverem aos seus sites, mais publicidade e mais cara conseguem vender. E se é certo que os agregadores passaram a ficar com parte dessa publicidade, por terem encontrado formas melhores e mais apelativas de transmitir informação, esta lei não vai resolver esse problema. Em vez de criar uma lei para a Google, que vai impactar plataformas mais pequenas ou inovadoras, prejudicando o acesso dos cidadãos à informação, seria melhor fomentar acordos entre a Google e os editores de publicações de imprensa, como aconteceu <a href="https://europe.googleblog.com/2012/12/partnering-with-belgian-news-publishers.html">na Bélgica</a>, <a href="https://blog.google/topics/google-europe/knowledge-for-everyone/">em França</a> com o French Innovation Fund ou através do <a href="https://newsinitiative.withgoogle.com/dnifund/">Digital News Innovation Fund</a>, que continua a apoiar os editores de publicações de imprensa, e do qual já <a href="http://www.twipemobile.com/projects-funded-by-google-digital-news-initiative-in-the-first-round/">beneficiaram no passado publicações como a Lusa e o jornal Público.</a></p>

<p>Não há necessidade de criar este direito conexo ao direito de autor. Os editores de imprensa alegam que o objectivo desta medida é fazer cumprir, na prática, o direito de autor. Para tal seria suficiente a consagração de uma presunção legal que permita aos editores de imprensa agir judicialmente, em nome dos seus jornalistas, contra eventuais infracções ao direito de autor.</p> 

<p>Por fim, mesmo no melhor cenário possível haverá sempre uma redução na circulação das notícias de jornalismo profissional (como assegura o advogado Thomas Hopper este é um direito de proibição). Haverá sempre publicações que não estão disponíveis para emitir licenças, haverá sempre agregadores que não poderão pagar licenças e haverá, como aconteceu em Espanha e na Alemanha, agregadores que não quererão pagar licenças.
A uma redução da circulação de notícias de jornalismo profissional corresponderá um aumento da circulação das chamadas “fake news”, uma vez que as pessoas não vão sair da Web, nem vão deixar de partilhar conteúdos. Os utilizadores partilham os conteúdos que os deixarem partilhar.
Há uns meses, o Facebook anunciou uma mudança no seu algoritmo que passaria a dar preferência a conteúdos de perfis (pessoas) em detrimento de conteúdos partilhados por páginas (jornais, revistas, marcas, e outras pessoas colectivas). A Folha de São Paulo  <a href="https://www1.folha.uol.com.br/poder/2018/02/fake-news-ganha-espaco-no-facebook-e-jornalismo-profissional-perde.shtml">fez algumas medições</a> das interações dos utilizadores com os conteúdos de publicações de imprensa e publicações de "fake news", entre Outubro de 2007 e Janeiro de 2018, observando naquele período uma diminuição da taxa média de interacções de 17% dos utilizadores com as notícias de jornalismo profissional, ao mesmo tempo que observou um aumento de 61,6% na taxa média de interacções dos utilizadores com “fake news” (11). É expectável que qualquer sistema que faça diminuir a circulação de notícias de jornalismo profissional, faça também aumentar a circulação de “fake news”, seja um algoritmo no Facebook ou uma lei deste tipo.</p>
```

**Comment by EdSantos754** [comment]
@marado atrapalhei-me no formato (com as tags de lista). Podes dar um jeito? O texto acima já tem todos os links e parágrafos.
