### ISSUE TITLE
Arranjar icones novos para as 6 secções a preto

### ISSUE THREAD

**Issue by EdSantos754** [marado/mp#6]

**Comment by marado** [comment]
Os "ícones" que aí estão a ser usados fazem parte da "font awesome", dá para ver e escolher outros aqui:
https://fontawesome.com/icons?d=gallery

Não quer dizer que não possamos mudar, mas aí tem provavelmente um símbolo bom para cada um dos items... só preciso que me digam quais para o quê.

Vou mudar para uns que me parecem mais adequados, mas se quiseres ainda melhores... diz só quais e onde :-)
