### ISSUE TITLE
Os 6 pontos sobre o artigo 13

### ISSUE THREAD

**Issue by EdSantos754** [marado/mp#7]
Na carta original, tínhamos 7 pontos. Eu elaborei um pouco mais um deles (utilizadores culpados até prova em contrário), e coloquei de fora outro (não estava completo), que se segue:

> 6) Irá fazer desaparecer os recursos educativos abertos, assim como a publicação de artigos científicos em acesso aberto
> 
> É impossível criar recursos educativos ou artigos científicos sem reutilizar partes ou excertos de outras obras. Quando um filtro automático encontrar uma parte ou excerto de outra obra irá impedir a publicação do recurso ou do artigo. Será impossível

Discutir: O que fazer com este ponto. Pode ser integrado noutros? Paula, penso que ele era teu. Que achas? Podemos integrar no ponto que refere explicitamente que os filtros não distinguem utilizações. Este ponto dos filtros tb precisa de um título melhorzinho.

Cumps

**Comment by paulasimoes** [comment]
Pode ser integrado sim, a ideia era sublinhar que isto atinge não apenas recursos educativos e artigos científicos fechados, mas também aqueles que são abertos.

**Comment by paulasimoes** [comment]
@marado porque é que isto é um bug?

**Comment by marado** [comment]
É uma coisa no texto que precisa ser corrigida (para ter o assunto integrado), pelo que interpreto. Se for apenas uma melhoria... Bem é só uma questão de prioridades :-)

**Comment by marado** [comment]
Alguém quer fazer uma proposta concreta de como alterar ou o que acrescentar ao texto actual?

**Comment by paulasimoes** [comment]
Sugestão: como o @EdSantos754 diz integrar o texto no ponto dos filtros não distinguirem utilizações:

Esta lei irá ainda fazer desaparecer os recursos educativos abertos, assim como a publicação de artigos científicos em acesso aberto
É impossível criar recursos educativos ou artigos científicos sem reutilizar partes ou excertos de outras obras. Quando um filtro automático encontrar uma parte ou excerto de outra obra irá impedir a publicação do recurso ou do artigo, uma vez que os filtros são cegos às excepções. Mesmo que os autores dos recursos ou artigos queiram publicá-los em acesso aberto.
